languages:
   JavaScript: true
engines:
  eslint:
    enabled: true
  fixme :
    enabled: true
ratings:
   paths:
   - honey.js
exclude_paths:
- "test/*"
- "honey.min.js"
- "Gruntfile.js"
eslint:
  enabled: true
  config:
    config: ./.eslintrc